### ISSUE TITLE
getting error while using command "sudo && sudo make install"

### ISSUE THREAD

**Issue by Akhilesh-prob** [SimplyCEO/rtl8188eus#14]
so basically i am getting this error and unable to proceed futher. my current system verion of is 6.6.18 and i am a beginner in kali linux or basically noob in other words can someone help me with this by providing whole commands froom start to end PLEASE.
and which kernel version of kali is supported to this rtl8188eus driver ? I AM STRUGGLING FOR PAST 5 DAYS OR MORE 
PLEASE HELP !!
![Screenshot (80)](https://github.com/user-attachments/assets/61d144bb-1ddb-4b65-8a3d-823dac9a9a2e)

**Comment by SimplyCEO** [comment]
It is written there `make[1]: *** /lib/modules/6.6.15-amd64/build: No such file or directory. Stop.` and it is told in the [documentation](https://github.com/SimplyCEO/rtl8188eus/blob/9c0784498e5008f947e58674e440da331f7e400c/docs/BUILDING.md?plain=1#L36).
You are missing the headers for building the driver.

By the way, I noticed that you are using the `aircrack-ng` repository,
This repository here is meant to be a bleeding edge patch, that works with the newest available stable kernel version.

If, after installing the headers, something gives an error, consider [posting an issue there](https://github.com/aircrack-ng/rtl8188eus/issues) or switching to this repository.

**Comment by Akhilesh-prob** [comment]
Thank you so much for the info but I have already solved the error appreciate your efforts. I just wanna know other than aircrack ng or any other they need word list file which contains the passwords but is there any other way to crack a wifi password without using the word list as of the wordlist doesn't contains the passwords of the wifi I am trying crack

**Comment by SimplyCEO** [comment]
You mean generating a "word list" on demand, using nothing but CPU/GPU power that could lead to many days of trying? `crunch`

**Without any word list method**

First you might want to check if the tower has WPS.
If so, try on it with a little bit of delay to not trigger the protection.

If not, check if the key is WPA2 or WPA.
WPA is more likely to crack without a word list.

If all these fail, use Evil Twin Attack.
It depends on another person to input the password, so use it to educate people.
